version: '3.9'

services:
  #--- LOAD BALANCER ---
  nginx:
    image: nginx:1.25-alpine
    container_name: rinha-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - rinha-net
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "15MB"

  api1: &api
    build: .
    hostname: api1
    environment:
      - APP_PORT=8080
      - DB_URL=postgres://user:password@db:5432/rinha?sslmode=disable
      - REDIS_URL=redis:6379
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - INSTANCE_ID=API-1
      - WORKER_CONCURRENCY=16
    networks:
      - rinha-net
      - payment-processor-net
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "30MB"

  api2:
    <<: *api
    hostname: api2
    environment:
      - APP_PORT=8080
      - DB_URL=postgres://user:password@db:5432/rinha?sslmode=disable
      - REDIS_URL=redis:6379
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - INSTANCE_ID=API-2
      - WORKER_CONCURRENCY=16


  #--- BANCO DE DADOS ---
  db:
    image: postgres:16-alpine
    container_name: rinha-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=rinha
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - rinha-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d rinha"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "115MB"

  #--- FILA E CACHE ---
  redis:
    image: redis:7.2-alpine
    container_name: rinha-redis
    command: redis-server --save "" --appendonly no --maxclients 20000
    networks:
      - rinha-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "40MB"

#--- VOLUMES E REDES ---
volumes:
  pg_data:
  redis_data:

networks:
  rinha-net:
    driver: bridge
  payment-processor-net:
    name: payment-processor
    external: true